INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = JoeTheGoose
JoeTheGoose_FILES = PXJoeTheGooseMod.m
JoeTheGoose_CFLAGS = -fobjc-arc
JoeTheGoose_INSTALL_PATH = /Library/Application Support/MobileGoose/Mods
JoeTheGoose_FRAMEWORKS = UIKit Foundation

include $(THEOS_MAKE_PATH)/bundle.mk
