#!/bin/sh

mv() {
	command mv "/Library/Application Support/MobileGoose/$1/"* "/Library/MobileGoose/$1/" 2> /dev/null > /dev/null || true
}

function finish() {
	f="${1}"

	# No control fd: bail out
	[[ -z "${f}" || -z "${CYDIA}" ]] && return
	cydia=(${CYDIA})

	# Cydia control fd version != 1: bail out
	[[ ${cydia[1]} -eq 1 ]] || return

	echo "finish:${f}" >&${cydia[0]}
}

case "$1" in

	triggered)
		echo "MobileGoose mods were changed, requesting a respring..."
		finish reload
		;;

	configure)
		mv Memes
		mv Notes

		rm -rf "/Library/Application Support/MobileGoose/Memes" "/Library/Application Support/MobileGoose/Notes" || true
		rmdir "/Library/Application Support/MobileGoose/Mods" 2> /dev/null > /dev/null || true
		rmdir "/Library/Application Support/MobileGoose" 2> /dev/null > /dev/null || true
		;;

esac