#!/bin/sh

mv() {
	command mv "/Library/Application Support/MobileGoose/$1/"* "/Library/MobileGoose/$1/" 2> /dev/null > /dev/null || true
}

finish() {
	action="${1}"

	# No control fd: bail out
	[ -z "${action}" || -z "${CYDIA}" ] && return

	fd_version=
	fd=
	i=0
	for item in ${CYDIA}; do
		case "${i}" in
			0) fd="${item}";;
			1) fd_version="${item}";;
		esac
		i=$((i+1))
	done

	# Cydia control fd version != 1: bail out
	[ "${fd_version}" -eq 1 ] || return

	echo "finish:${action}" >&${fd}
}

case "$1" in

	triggered)
		echo "MobileGoose mods were changed, requesting a respring..."
		finish reload
		;;

	configure)
		mv Memes
		mv Notes

		rm -rf "/Library/Application Support/MobileGoose/Memes" "/Library/Application Support/MobileGoose/Notes" || true
		rmdir "/Library/Application Support/MobileGoose/Mods" 2> /dev/null > /dev/null || true
		rmdir "/Library/Application Support/MobileGoose" 2> /dev/null > /dev/null || true
		;;

esac