INSTALL_TARGET_PROCESSES = SpringBoard

include @@THEOS@@/makefiles/common.mk

BUNDLE_NAME = @@PROJECTNAME@@
@@PROJECTNAME@@_FILES = @@CLASSNAME@@.m
@@PROJECTNAME@@_CFLAGS = -fobjc-arc
@@PROJECTNAME@@_INSTALL_PATH = /Library/MobileGoose/Mods
@@PROJECTNAME@@_FRAMEWORKS = UIKit Foundation

include $(THEOS_MAKE_PATH)/bundle.mk
